### ISSUE TITLE
Basic features

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/act#1]
Creating this issue to track the basic features that the spec language should have.

Initial items I and @MrChico came up with:

- Contract invariants
- Functions pre and post conditions
- Blockchain context

Hopefully the result of discussions here will be the agreed basic set of features.

**Comment by wuestholz** [comment]
Great! That sounds like a good start. :)

Just to clarify: by contract invariants you're referring to invariants that hold after construction and  before and after each contract invocation, right?

What exactly do you have in mind for "blockchain context"?

Would we want something like modifies clauses for functions?

**Comment by MrChico** [comment]
Some initial thoughts.
The `act` https://github.com/dapphub/klab/blob/master/acts.md language was developed for specifying pre and post conditions of contract methods to be proven using KEVM, and is in my opinion quite intuitive and well suited for this task. It borrows some conventions from solidity, but is otherwise pretty much "mathy english"; it describes the state transitions in terms of updates to storage, which is understood as a key-value mapping of variable names or mappings to values, expressed as (true) integer expressions. 

If this language gets some love, it could be extended to support multiple backends. I'd be happy to collaborative here. My initial plan is to add extend the preliminary haskell parser of `act` (https://github.com/dapphub/klab/blob/haskell-act-parser/haskell/klab-build/src/Parser.hs) with some integer theory in order to factor out some of the K specific elements of Acts in order to make it a more flexible front end specing language. My first second backend would be the solidity SMT checkers (function pre-post).

Then we can think about a nice syntax for specifying contract invariants.

As for the `blockchain context`, what I think @leonardoalt is alluding to is making claims about the properties of contracts with the respect to their behaviour when it comes to chain reorderings, frontrunning, eclipse attacks, spam / censorship and stuff like this. Which is interesting to think about, but hard to come up with any general ideas for (at least for me) insofar as a specing language is concerned.

**Comment by dddejan** [comment]
This is of interest to us, so just leaving a note.

We're working on a Solidity verifier that can prove specs as described by @leonardoalt (I don't know if this effort is more general, Vyper etc). We chose Solidity (with some extensions) for our spec language, and we keep the specs within comments. Basic examples can be seen [here](https://github.com/SRI-CSL/solidity/blob/boogie/test/solc-verify/examples/Annotations.sol) and more detailed examples [here](https://github.com/SRI-CSL/solidity/tree/boogie/test/solc-verify/specs). We're interested in improving the spec language for developers, so any feedback is appreciated.

We can provide more input for discussion if needed but our main philosophy is that the specs should be in the language of the developer (i.e., Solidity) and should be part of the code that doesn't compile. This is so that developers understand what they are writing and so that it is visible as part of the API (e.g. on Etherscan).

That said, we are interested in a common spec language and will definitively support it, specially if it supported by the compiler.

**Comment by franck44** [comment]
Hi all, 

I recently joined PegaSys and my background is in automated software verification techniques and tools.

Reading the comments above, the following may be of interest.

**Language features**
Dafny (https://www.microsoft.com/en-us/research/project/dafny-a-language-and-program-verifier-for-functional-correctness/) is a verification-friendly/aware language with pre/post conditions and automatic verification support (default backend  is Z3, but other SMT-solvers can be selected).

In the realm of languages for smart contracts, IOHK has recently released Plutus (ttps://testnet.iohkdev.io/plutus/) which may be worth looking at.

DigitalAssets has also a smart contract language DAML.

**Verification**
When considering verification and language design, it may be useful to take into account language 
constructs/features that can make the verification steps easier.

There are quite a lot of automatic verification techniques/tools (e.g. abstraction refinement) that may be ported to spec languages for smart contracts (or languages smart contracts can be compiled to liked WASM).

Another consideration may be the concurrent nature of smart contracts (if I am correct, smart contracts may run in parallel and proving correctness may require taking into account concurrent processes). Invariants and pre/post conditions (Hoare logic) are good for sequential programs, but harder to use in a concurrent setting (Owicki-Gries logic extends Hoare).

I am happy to provide more information if you think it is useful.

**Comment by leonardoalt** [comment]
@wuestholz 
< Just to clarify: by contract invariants you're referring to invariants that hold after construction and before and after each contract invocation, right?

Exactly.

@MrChico 
I really like `act`. It's simple, already supports functions pre/post, and I like the "mathy english". I'm not a fan of some particular syntax elements, and I think it could be a little more high level (or at least give the option) with respect to storage, but I think it's a good direction.

@dddejan 
I totally see your points, but the effort here is to come up with a simple spec language that multiple tools would support, regardless whether they verify Solidity, Vyper, EVM, eWasm. I will update the README with this kind of things. That said, we can definitely get some input from your specs. Ideally, the compiler would also support the language in potentially different ways.

@franck44 Thanks!
I quite like Dafny and think we could use some ideas from it.
> There are quite a lot of automatic verification techniques/tools (e.g. abstraction refinement) that may be ported to spec languages for smart contracts

Do you mean they could output specs or use the smart contract specs as inputs? In the latter case, what would it do with it?

Re concurrency, smart contracts cannot run in parallel. You can't guarantee the order of transactions, but in a single transaction the execution is fully sequential.

**Comment by wuestholz** [comment]
I agree with @dddejan that it's good to keep the language high-level for now by focusing on something that the developer/auditor can understand. This means anything that implicitly assumes something about the EVM representation of certain constructs (e.g., storage slots) should probably be avoided. The same holds for any non-trivial math or logic (e.g., maybe things like temporal logic could later be incorporated as extensions if there is a need).

It would be nice to write the specifications at the level of the ABI; that definitely should be possible for many pre- and postconditions (modifies clauses are more difficult since they refer to state that is not publicly accessible). That might also make them less Solidity-specific.

**Comment by leonardoalt** [comment]
I totally agree, that's what I meant with `I think it could be a little more high level (or at least give the option) with respect to storage` in my previous comment.

@wuestholz I also agree with writing the spec at the level of the ABI. The way I see it, that's pretty much what `act` does (except the storage part). @MrChico told me today that the plan there is anyway to provide higher level ways to reason about storage.
Although, I think doing that at the ABI level wouldn't make it less Solidity-specific, since the ABI spec is pretty much written by Solidity.

**Comment by franck44** [comment]
> @leonardoalt 
> I quite like Dafny and think we could use some ideas from it.

Yes me too :-)
 
> > There are quite a lot of automatic verification techniques/tools (e.g. abstraction refinement) that may be ported to spec languages for smart contracts
> 
> Do you mean they could output specs or use the smart contract specs as inputs? In the latter case, what would it do with it?

Software model-checkers can analyse source code. So you can have a smart contract as input (this is code). 
Various types of analysis are supported. The overarching one is reachability analysis.
For languages like C for instance, you can check for null pointer dereference (is there an execution path leading to a null pointer deref?), or division by zero and so on.

**Comment by leonardoalt** [comment]
Closing this issue since we now have basic structure and syntax, as show in the `examples` directory.
