### ISSUE TITLE
hevm build errors in nix-shell

### ISSUE THREAD

**Issue by xwvvvvwx** [ethereum/act#24]
I'm getting some build errors in `hevm` when I run `nix-shell` from the project root: 

```
Setup: Missing dependency on a foreign library:
* Missing (or bad) C library: ff
```

full log: https://ipfs.io/ipfs/QmQ7dYfuhzQtJSNAssx2EtszXxyMmWaeqLPHTVfFKHnYaA/out.log

Any idea whats going on?

**Comment by endorphin** [comment]
I'm not sure, although it looks like this has come up before:

https://github.com/dapphub/dapptools/issues/223

If you haven't already, check that you're on a relatively recent nixpkgs (I just checked that it builds for me on the current 19.09 stable channel).

Otherwise, I have occaisionally had permissions issues with C library files in `/nix/store` needed by ocaml libs, so it could be something like that.

**Comment by xwvvvvwx** [comment]
@endorphin I'm building with `nixpkgs` pinned in the `shell.nix` to `19.09@8260cd5bc65fad88ad8881b32c990e5659cc417a`, so I don't think that's the problem. :thinking:

**Comment by MrChico** [comment]
Hmmm, it _should_ be configured here https://github.com/dapphub/dapptools/blob/91d7226f2f12453dbc867faa58db2a4342bea479/haskell.nix#L52
