### ISSUE TITLE
Decide on Semantics for Variable References in the Ensures Block

### ISSUE THREAD

**Issue by xwvvvvwx** [ethereum/act#92]
As currently implemented, storage references in the `ensures` blocks refer to the value of that variable in the prestate. This semantics was chosen to keep the meaning of an expression consistent throughout the behaviour. This does however allow the construction of some perhaps surprising behavioiurs.

For example the following spec will fail when run with `act prove`:

```
behaviour f of C
interface f()

storage

  x => 2

ensures

  x == 2
```

This is because in the expression in the `ensures` block, `x` is refering to the value of that storage slot in the *prestate*. While a consistent semantics for expressions throughout a behaviour is a nice property, the current situation is quite unintuitive. I can see a few options:

1. Change the semantics of the `ensures` block to make storage references refer to the poststate
2. Introduce syntax that allows users to explicitly refer to the poststate (e.g. `post(x)`)
3. Keep the current semantics, and instead allow users to define per spec variables (in a `where` clause). This would allow specs to look something like the following:

```
behaviour f of C
interface f(uint a)

storage

  x => xPost

ensures

  xPost >= 2

where

  xPost := 2 + a * 5
```

@MrChico @leonardoalt interested to hear your thoughts here.

**Comment by leonardoalt** [comment]
I think my favorite (and in my opinion most intuitive) option is 1.

**Comment by kjekac** [comment]
I think I prefer option 2, but would suggest the syntax `x'` instead of `post(x)` since it's cleaner and relatively consistent with notation often used in logic/discrete math. As far as I know `'` is already disallowed in identifier names so making it a postfix operator shouldn't be intrusive.

I agree that 1 is intuitive in a sense but I think that less magic/ambiguity is better. Of course this would not *technically* be an ambiguity, but from just looking at a spec it isn't entirely *obvious* that the same identifier refers to different things in different sections. I would prefer it if it was in fact *obvious* what a given spec was saying, to the degree that this is possible.

**Comment by MrChico** [comment]
In the previous act syntax, the matter was a lot clearer since there was an explicit distinction between the pointer and its value.
```
storage
    X |-> X_PRE => X_POST
```

However, this was quite verbose, especially since we enforced that every variable needed to be declared in a `forall` block.

The new syntax introduced a "abuse of notation" to let the left hand side of storage update denote both the name of the storage variable and its pre value.

What is being suggested here is essentially breaking purity and referential transparency from act specs as a whole, by letting the value of `x` change value over the spec. 

I feel like there are two directions here. One in which we abandon referential transparency, and let values change over the spec. In this scenario, I don't see much of a reason to not introduce an ordering to the rewrites as well. At this point we really have a sort of imperative language with proofing tools.

In the other direction, we reintroduce syntax to make the distinction between variables and their values. This distinction might actually be useful after all. In `invariant` blocks, and maybe also `ensures` blocks, we could introduce some pointer symbols to fetch the values at certain locations.

**Comment by kjekac** [comment]
How does option 2 (or 3, for that matter) break purity/referential transparency? It seems like option 3 is exactly the same situation that we have at the moment, while option 2 would introduce an additional operator but no mutability or other imperative features. But maybe I'm missing something?

**Comment by MrChico** [comment]
They would not, I was referring proposition 1 in the above. I have edited the above to clarify

**Comment by kjekac** [comment]
Ok, so then commenting on your two directions:

>[Abandon] referential transparency [...] At this point we really have a sort of imperative language with proofing tools.

I don't think this is a desirable to go in. Of course the distinction between implementation language and specification language is always going to be somewhat blurry but I think the specification niche is more important for us to fill and has less competition.

>[Reintroduce] syntax to make the distinction between variables and their values. This distinction might actually be useful after all.

Maybe. I'm not *principally* against it but I haven't seen proof of its usefulness yet, given that I think we already have an adequate and more intuitive solution which also introduces less cognitive overhead (namely option 2). But maybe there are other situations distinguishing between variables and their values would be necessary or provide greater relative benefits? (Of course they aren't mutually exclusive either, so if one solves some things better and vice versa for other things, we can have both.)

What is your opinion on option 2, temporarily disregarding the concrete syntax?

**Comment by MrChico** [comment]
I'm not strongly opposed to the `post` operator. But I think that even if we introduce a new syntax for denoting the post state of a variable we may still have this confusion where one might have the intuition that `x` should already denote the post state in the `ensures` section.

**Comment by kjekac** [comment]
Conclusion from the call today seems to be to force the use of `pre(x)` and `post(x)` for the time being.
